### ISSUE TITLE
Windows Spotlight gone black !

### ISSUE THREAD

**Issue by prakasharyaman** [BenoitEirik/Wallpaper-Of-The-Day#1]
HI, i just installed your script as per your instructions and it did not worked for me so i deleted the wotd file and the task scheduler and was able to set my own wallpaper but now my windows spotlight doesn't work and it just shows a black image and when i try to change it the following shows on the spotlight settings screen :

<img width="714" alt="image" src="https://user-images.githubusercontent.com/63445447/157209014-4563b19a-8483-4166-90df-b697a925c9f8.png">

**Comment by BenoitEirik** [comment]
Hi @prakasharyaman ,

To be able to change the lockscreen wallpaper again, you must delete a set of registry keys. To do this, delete the folder in your registry:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP`
The folder to delete is `PersonalizationCSP`

If you don't know how to open the registry : [link](https://support.microsoft.com/en-us/windows/how-to-open-registry-editor-in-windows-10-deab38e6-91d6-e0aa-4b7c-8878d9e07b11)

Tell me if it doesn't work.
I'll update my script soon to uninstall and clean properly the register.

**Comment by prakasharyaman** [comment]
> Hi @prakasharyaman ,
> 
> To restore the wallpaper you must delete a set of registry keys. To do this, delete the folder in your registry:
> `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP`
> 
> If you don't know how to open the registry : [](https://support.microsoft.com/en-us/windows/how-to-open-registry-editor-in-windows-10-deab38e6-91d6-e0aa-4b7c-8878d9e07b11)
> 
> Tell me if it doesn't work.
> I'll update my script soon to uninstall and clean properly the register.
(I'll try this )
I guess adding uninstall in your script would be a nice addition.

**Comment by prakasharyaman** [comment]
I will try it out 
Although , adding a uninstall method in your script would be a huge help for future users.

**Comment by prakasharyaman** [comment]
the solution you gave me did work and thank you

**Comment by BenoitEirik** [comment]
I will check that everything works by reinstalling and following the steps I indicated in my README.md file
I already have see I did some big errors.

**Comment by prakasharyaman** [comment]
the -dest method doesn't run correctly in win 11 

> (it just generates files in the same folder and not in c://wotd , it has to de done by hand)

(i did run using administrator power) 
uninstalling :
>  it leaves a lot of residue files in various places like c://wotd and a task scheduler which could be avoided by a simple uninstall method .
**should probably build an .exe program using some low end framework as installing the app WOTD will be easier**

**Comment by BenoitEirik** [comment]
@prakasharyaman ```-Dest``` method is now working
I will add an uninstalling method later but I don't want to build an ```.exe```, I thank about it but I wanted to do a simple script and I don't know .NET very well.
Maybe be later.

**Comment by prakasharyaman** [comment]
Very well @BenoitEirik .
I guess the script will have to do , it's very good and simple .
Good job 👌 &
Godspeed.

**Comment by prakasharyaman** [comment]
hey , so i experimented your script on a few devices and i noticed that by default , the task only runs when windows is on Ac power . i had to manually deselect the **Start only if on Ac power** in task settings in task scheduler. 
you can add this in readme.md of your project so future users can understand the problem .

**Comment by BenoitEirik** [comment]
@prakasharyaman Hello,
I took into account what you told me. The wallpaper will be applied on battery.
I also solved other problems.

Thank you for your interest.

**Comment by BenoitEirik** [comment]
@prakasharyaman I recently update the repository because I got an error when destination path had space in path.
I forgot also to remove task scheduled.
